global:
  smtp_smarthost: 'mailpit:1025'
  smtp_from: 'alertmanager@test.com'
  smtp_require_tls: false

route:
  receiver: email

receivers:
  - name: email
    email_configs:
      - to: 'developer@test.com'
