groups:
  - name: AllInstances
    rules:
      - alert: InstanceDown
        expr: up == 0
        for: 1m
        annotations:
          title: "Instance {{ $labels.instance }} down"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute."
        labels:
          severity: "critical"
  - name: Service
    rules:
      - alert: "Service"
        expr: 'absent(container_tasks_state{state="running",name="my-service"})'
        for: 1m
        annotations:
          title: "Container my-service down"
          description: "my-service has been down for more than 1 minute."
        labels:
          severity: "critical"
